"""add signups table

Revision ID: 2368ce5ea68b
Revises: dd92a9a3a0a6
Create Date: 2026-09-07 18:53:35.368367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2368ce5ea68b'
down_revision: Union[str, Sequence[str], None] = 'dd92a9a3a0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signups_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_signups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signups_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signups_source'))
        batch_op.drop_index(batch_op.f('ix_signups_id'))
        batch_op.drop_index(batch_op.f('ix_signups_email'))

    op.drop_table('signups')
    # ### end Alembic commands ###
