"""Normalize to 3NF

Revision ID: 49a7fe414afe
Revises: 146d56fe1c33
Create Date: 2026-07-06 15:34:51.881610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a7fe414afe'
down_revision: Union[str, Sequence[str], None] = '146d56fe1c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    
    op.create_table('blog_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('point_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_points_id'), 'blog_points', ['id'], unique=False)
    
    op.create_table('blog_category_links',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('blog_id', 'category_id')
    )

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('categories')
        batch_op.drop_column('category')
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.VARCHAR(), server_default=sa.text("'[]'"), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), server_default=sa.text('("")'), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(), server_default=sa.text("'[]'"), nullable=True))

    # ### end Alembic commands ###
