"""add rag tables

Revision ID: 4dbff2491d5f
Revises: c72ac90486cd
Create Date: 2026-08-04 15:13:16.054787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbff2491d5f'
down_revision: Union[str, Sequence[str], None] = 'c72ac90486cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('stage_timings', sa.JSON(), nullable=True),
    sa.Column('retrieval_scores', sa.JSON(), nullable=True),
    sa.Column('rerank_scores', sa.JSON(), nullable=True),
    sa.Column('aggregate_confidence', sa.Float(), nullable=True),
    sa.Column('fallback_triggered', sa.Boolean(), nullable=True),
    sa.Column('chosen_image', sa.String(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_traces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_traces_session_id'), ['session_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('rag_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_traces_session_id'))
        batch_op.drop_index(batch_op.f('ix_rag_traces_id'))
        batch_op.drop_index(batch_op.f('ix_rag_traces_created_at'))

    op.drop_table('rag_traces')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
