"""add inquiry handled flag and sync_runs table

Revision ID: 5c48b7eb1cb4
Revises: 4dbff2491d5f
Create Date: 2026-09-04 12:55:37.303340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c48b7eb1cb4'
down_revision: Union[str, Sequence[str], None] = '4dbff2491d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('files_processed', sa.Integer(), nullable=True),
    sa.Column('chunks_indexed', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_status'), ['status'], unique=False)

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('handled')

    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_id'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_finished_at'))

    op.drop_table('sync_runs')
    # ### end Alembic commands ###
