"""add inquiries table

Revision ID: c72ac90486cd
Revises: 49a7fe414afe
Create Date: 2026-09-04 11:19:28.102975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72ac90486cd'
down_revision: Union[str, Sequence[str], None] = '49a7fe414afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_mode'), ['mode'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_mode'))
        batch_op.drop_index(batch_op.f('ix_inquiries_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_email'))

    op.drop_table('inquiries')
    # ### end Alembic commands ###
