"""add notify_email and notify_name to inquiries

Revision ID: dd92a9a3a0a6
Revises: 5c48b7eb1cb4
Create Date: 2026-09-07 18:42:14.078850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd92a9a3a0a6'
down_revision: Union[str, Sequence[str], None] = '5c48b7eb1cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notify_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('notify_name')
        batch_op.drop_column('notify_email')

    # ### end Alembic commands ###
